### ISSUE TITLE
Error: "rtons\pp.rton pos 10427: unpack requires a buffer of 1 bytes"

### ISSUE THREAD

**Issue by Drazzii** [Nineteendo/PVZ2tools#1]
Got the latest version, tried to convert and got this error. This happens with the file being pp.dat, pp.rton, and pp.dat.rton. File provided.

[pp.zip](https://github.com/Nineteendo/PVZ2tools/files/6588996/pp.zip)

**Comment by Nineteendo** [comment]
Your file abruptly stops: 910A2401 91??
but even if it didn't you can correctly convert it back.
Sorry, currently working on that.

**Comment by Drazzii** [comment]
Alright. Hopefully a way can be figured out. As far as I can tell, you are the only one actively working on a program, and able to receive input.
