### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by UCYT5040** [Nineteendo/PVZ2tools#15]
The tool finishes very quickly, then nothing happens. The output file is empty.

**Comment by Nineteendo** [comment]
Is there just a slash on the screen? In that case go out of the app and try launching the script again. Repeat until it works.

**Comment by UCYT5040** [comment]
No it says completed in x seconds or something like that. It looks like it worked but the output file is empty.

I'm also using the RSB file in PvZ1, maybe that effects it?

**Comment by Nineteendo** [comment]
What are you trying to do? Extracting files from pvzfree with DEFAULT TEMPLATE? In that case you should use Unpack Everything instead.

**Comment by UCYT5040** [comment]
How?
