### ISSUE TITLE
zlib.error: Error -5 while decompressing data: incomplete or truncated stream

### ISSUE THREAD

**Issue by qnmakingstupidstuff** [Nineteendo/PVZ2tools#19]
Hello your tool crashed [OBB](https://mega.nz/folder/42BS2YaK#zB-rZDBaYGRVi0YXrQcQVA)

**Comment by harumatool-admin** [comment]
:>

**Comment by Nineteendo** [comment]
Are you using the alpha version from GitHub? I'll check when the file is downloaded.

**Comment by Nineteendo** [comment]
[fail.txt](https://github.com/Nineteendo/PVZ2tools/files/10148558/fail.txt)
I was already thinking, hmm 700 errors seems a bit much for just empty RSGs...

**Comment by harumatool-admin** [comment]
It's not empty RSGP, just your tool can't unpack it

**Comment by Nineteendo** [comment]
![Screenshot_20221204-141919](https://user-images.githubusercontent.com/65588599/205493258-2ed2a09b-b028-45c4-ad7d-ef173da1c9a6.png)
Fixing my code...

**Comment by Nineteendo** [comment]
OK, should be fixed on the alpha version as well.
I'll close this with the next release.

**Comment by Nineteendo** [comment]
[PVZ2tools-alpha.zip](https://github.com/Nineteendo/PVZ2tools/files/10148626/PVZ2tools-alpha.zip)
There may come more fixes in the future, so I suggest following my discord server as I won't upload versions edited on mobile...

**Comment by qnmakingstupidstuff** [comment]
hi, sorry for bothering you again. can you tell me why some obb the subgroup name is very long like this one? i will close this issue once this question is answered, thank u

**Comment by Nineteendo** [comment]
> hi, sorry for bothering you again. can you tell me why some obb the subgroup name is very long like this one? i will close this issue once this question is answered, thank u

The reason it's so long is because the 128 bytes are hex encoded, resulting in at most a 256 name. I'll close this issue when it's fixed in a release.

**Comment by qnmakingstupidstuff** [comment]
okay, thank you for replying me! I don't really understand much but still thank you

**Comment by Nineteendo** [comment]
It's fixed on alpha, but it has not yet been fixed in a release, beta or stable version.
