### ISSUE TITLE
AttributeError: 'str' object has no attribute 'removesuffix' when converting json to rton

### ISSUE THREAD

**Issue by mutaqin-hanif** [Nineteendo/PVZ2tools#4]
![IMG_20220201_100933](https://user-images.githubusercontent.com/44286875/151907655-bbdc80d4-a461-4b1e-a09b-aaa23ca26187.jpg)

**Comment by mutaqin-hanif** [comment]
Using termux btw, but it's working well on windows

**Comment by Nineteendo** [comment]
- You can set DEBUG_MODE in options.json to true to provide me with extra information.
- You can provide me with the json so I can test myself.

**Comment by mutaqin-hanif** [comment]
Ah i see, now i've upgrade it and it's work thanks 👍

**Comment by Nineteendo** [comment]
Now trying to using a version under 3.9 will stop the parser immediately.
