### ISSUE TITLE
Jsonpatchwork exe

### ISSUE THREAD

**Issue by Tre-VN** [Nineteendo/PVZ2tools#41]
Hi I want to build exe of your tool, the tool always crash when I launch it. Could you help me merge all the files into onefile and help me fixing the issue?
![image](https://user-images.githubusercontent.com/114157573/212636268-534e6bc8-e16c-4e0b-8761-5d3b2050a89b.png)

**Comment by Tre-VN** [comment]
This is the bug when console to the terminal
![image](https://user-images.githubusercontent.com/114157573/212641579-8c474898-a34c-4224-9235-51ae47f40c77.png)

**Comment by Nineteendo** [comment]
Have you ran it with
```shell
$pyinstaller --onefile jsonpatcher.py
```
You also need the libraries.

**Comment by Tre-VN** [comment]
Already did, if you take a look at the dist it is the result after pyinstaller

**Comment by Nineteendo** [comment]
Well, not sure what's going wrong here. I can't reproduce this without the exe
