### ISSUE TITLE
More information in Manually Template

### ISSUE THREAD

**Issue by Haruma-VN** [Nineteendo/PVZ2tools#55]
Manual Template in the tool is too hard to use, the input force the user have to guess because no details information.
The tool must provide more information.
Example:
ZIP Unpack Level (1 - 2)
1. Skip this process
2. Unzip

![image](https://user-images.githubusercontent.com/114157573/219857158-2a871fed-e08b-46ea-81a2-db554a6ce980.png)

**Comment by Nineteendo** [comment]
Sorry, but you'll have to give me more information.

**Comment by Nineteendo** [comment]
Is it now better now that you don't need to skip? (As now only one conversion is performed per template)

**Comment by Nineteendo** [comment]
Stale issue. Closed.
