### ISSUE TITLE
ModuleNotFoundError: No module named 'libraries'

### ISSUE THREAD

**Issue by KildButCooler** [nineteendo/pvz2tools#59]
![](https://i.gyazo.com/510889e4bfa8fd7a58448cdd3dec3bc2.jpg)

**Comment by Nineteendo** [comment]
Yeah, that has to do with storage access framework I would need to check if there's a work-around. But currently I don't have time.

**Comment by Engjell420** [comment]
Im having this exact issue, any fixes yet?

**Comment by nineteendo** [comment]
Sadly not, you'll have to be patient since I'm kind of busy.

**Comment by Engjell420** [comment]
Thats alright, im not goona force you to fix it, sometimes fixing it can surface a lot more bugs anyway, i found that you can use qpython and not pydroid to unpack the files and it works until the template part but then it cant unpack the files to the obb- folder so its definitely a SAF issue.

**Comment by nineteendo** [comment]
- Have you tried open internal storage with the latest version of Pydroid 3? That seems to work on Android 14.
- You can also try moving the tool to `/storage/emulated/0/ru.iiec.pydroid3/files` and running it with "app storage, removed on uninstall".

**Comment by Engjell420** [comment]
> * Have you tried open internal storage with the latest version of Pydroid 3? That seems to work on Android 14.
> * You can also try moving the tool to `/storage/emulated/0/ru.iiec.pydroid3/files` and running it with "app storage, removed on uninstall".

Thanks for being so helpful both to me and the original poster, personally I adressed the issue by modding the game on my pc where I can run the app with admin rights.
Although the second step where you move the files to the local pydroid folder does seem to work on android 11.

**Comment by nineteendo** [comment]
Hmm, the first step works on Android 14. Did you update Pydroid 3?

**Comment by Engjell420** [comment]
> Hmm, the first step works on Android 14. Did you update Pydroid 3?

I am on android 11, app is updated and it did work, If you give the app full permissions over your files and you put the game files in a folder where the pydroid app can read/write/modify them, It will surely work.

**Comment by nineteendo** [comment]
Yes, but did it work by opening the file using the "Internal Storage" option and selecting it from `/storage/emulated/0/Download'?

**Comment by Engjell420** [comment]
Yes, it doesnt show the error mentioned in the post. I moved the pyvz2 tools in the storage/emulated/0/Android/data/ru.iiec.pydroid3 folder and ran the unpack.py file with app storage, removed on uninstall and it had no errors, i also did the internal storage method (if youre using internal storage just leave the pyvz2 tools in the downloads folder) and it worked both times, although for some reason it doesnt really unpack the files it just runs the script and thats it?
![Screenshot_20240201-012637_Pydroid 3](https://github.com/nineteendo/pvz2tools/assets/114947719/31a50a54-ef34-4cc2-80ba-36422e80930f)
Im probably doing something wrong but i followed the youtube tutorial step by step and when it "unpacks" the output directory has the original obb file and no unpacked folder.

**Comment by Engjell420** [comment]
Just tried unpacking again but this time with QPython because i dont know, i thought different apps might fix the issue but nope, same thing.
![Screenshot_20240201-015838_QPython](https://github.com/nineteendo/pvz2tools/assets/114947719/10547aae-99aa-43e8-8083-220cc4e1af17)
 Since im on android 11 i think this is an issue with my android version not giving apps full permission to read write or edit even when I checked the full permission to true in settings, it probably still doesnt let the app unpack files to the storage/emulated/0/Android/obb- folder, although changing the unpack.py input and output folder to something like storage/emulated/0/Downloads would probably work (because most apps have permission to the Downloads folder) but I dont know how to do that.

**Comment by nineteendo** [comment]
That means that the tool can't find the obb. I have to admit it doesn't make it obvious. Make sure that the obb is in `/storage/emulated/0/Android/obb-/com.ea.game.pvz2_row (1)`.
Also verify that the extension of the obb is still ".obb". Continue discussion in #66 if you're still having issues.
