### ISSUE TITLE
I can't download in view code

### ISSUE THREAD

**Issue by Hshshsveb** [Nineteendo/PVZ2tools#63]

**Comment by Nineteendo** [comment]
Did you try view desktop site?
![Screenshot_20230624-193505.png](https://github.com/Nineteendo/PVZ2tools/assets/65588599/39ae29eb-ea1b-4b4d-8c8a-9f14f0b953a7)
![Screenshot_20230624-193618.png](https://github.com/Nineteendo/PVZ2tools/assets/65588599/6aeb3065-cb2c-4296-b05f-b65fd57fba90)
