### ISSUE TITLE
can't see files

### ISSUE THREAD

**Issue by CubePvZ** [nineteendo/pvz2tools#64]
When I use the Pydroid 3, and then go to downloads > pvz2tools-master > obbedit, I can't see the unpack.py file and any other files. I can only see folders. Why??
![Screenshot_20230910-153300_Pydroid 3](https://github.com/Nineteendo/PVZ2tools/assets/144599040/0283dd08-88e4-4690-be34-4d44a4b7b509)

**Comment by nineteendo** [comment]
You have resolved the issue, so I'm closing this.
