### ISSUE TITLE
Compressed RSBs are not supported

### ISSUE THREAD

**Issue by Nineteendo** [Nineteendo/PVZ2tools#8]
Compressed Zlib smf files from inside the Chinese APK are not supported

**Comment by YingFengTingYu** [comment]
smf file structure:
0x0-0x3: magic number 0xD4 0xFE 0xAD 0xDE
0x4-0x7: file length
0x8-End: Zlib file

**Comment by Nineteendo** [comment]
Yeah it's as simple as implementing a Zlib file reader, but I'm currently working on some more urgent problems.

**Comment by Nineteendo** [comment]
Oh, actually kind of helpful. I didn't realize they had a header too.

**Comment by Nineteendo** [comment]
Implemented in Beta 1.1.4. Thanks so much for the help.
